### ISSUE TITLE
如何实现以VV开头的字符串（其中可能有a-zA-Z0-9），然后去掉VV这两个字母直接上屏？

### ISSUE THREAD

**Issue by netvolcano** [amzxyz/rime_wanxiang_pro#19]
有时候需要输入一串字符串（其中可能有a-zA-Z0-9），又不想切换到英语，就想用VV作为开头，怎样做才能去掉VV这两个字母、等我按回车后直接上屏那一串字符串？

**Comment by amzxyz** [comment]
1、有词典的方式
```    - affix_segmentor@VVVVVV  #英文模式```
```
VVVVVV:
  tag: VVVVVV
  dictionary: 词库
  enable_user_dict: false
  prefix: "VV"  
  tips: "  〔字符模式〕"
 ```
```
recognizer:
  import_preset: default  # 从 default.yaml 继承通用的
  patterns:  # 再增加方案专有的：
    VVVVVV "^VV([0-9]|10|[A-Za-z]+)$"    
```
```
alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`/
```
这里hold住

2、写个lua方式
