### ISSUE TITLE
关于自定义词库的疑惑

### ISSUE THREAD

**Issue by Mikachu2333** [amzxyz/rime_wanxiang_pro#72]
如题，我希望自定义词库，但是又不希望直接修改原词库，因此我在根目录下新建了一个索引词库 `custom_self.dict.yaml`，又在cn文件夹下新增了一些词库文件（这些词库是直接从其他方案迁移过来的，现在重新部署后可以正常输入且日志文件中无词库内容相关的报错），此外，我修改了custom文件，但日志中仍然报错，请问我该如何修正？

1. **日志提示**（由于全都是未找到文件的相同报错所以就不全放出来了）
```log
Log file created at: 2025/04/11 13:17:41
Running on machine: DESKTOP-3R7J65L
Running duration (h:mm:ss): 0:00:20
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20250411 13:17:41.431472 10716 mapped_file.cc:78] attempt to open non-existent file 'D:\Documents\Rime_config\build\wanxiang.table.bin'.
E20250411 13:17:41.432856 10716 table.cc:260] Error opening table file 'D:\Documents\Rime_config\build\wanxiang.table.bin'.
E20250411 13:17:41.432895 10716 dictionary.cc:368] Error loading table for dictionary 'wanxiang'.
E20250411 13:17:41.446937 10716 mapped_file.cc:78] attempt to open non-existent file 'D:\Documents\Rime_config\build\wanxiang.table.bin'.
E20250411 13:17:41.446983 10716 table.cc:260] Error opening table file 'D:\Documents\Rime_config\build\wanxiang.table.bin'.
```

2. `wanxiang.custom.yaml`

```yaml
patch:
  translator/dictionary: custom_self
```

3. `custom_self.dict.yaml`

```yaml
---
name: custom_self
version: "2025.4.11"
sort: by_weight  #字典初始排序，可選original或by_weight
use_preset_vocabulary: false
import_tables:
  - cn_dicts/chars            #字表，包含了所有带拼音的汉字
  - cn_dicts/base            #基础词库，2-3字词汇
  - cn_dicts/correlation     #关联词库，4字词汇，多为不同词频的2字语句连接起来起到合理组句的能力
  - cn_dicts/associational   #联想词库，5字以上词汇，多用于输入前半段第二候选可以出来整段
  - cn_dicts/corrections     #错音错字，支持错音和错字输入的兼容，同时供超级注释lua使用会在输入错误音节打出的时候给予提示
  - cn_dicts/compatible      #兼容词库，是基础词库的扩充，收录了多场景多种读音的词组
  - cn_dicts/poetry          #诗词
  - cn_dicts/place           #地名
  - cn_dicts/medical
  - cn_dicts/yuanshen
  - cn_dicts/kaomoji
...
```

4. 重新部署的build文件关键部分

```yaml
add_user_dict:
  dictionary: wanxiang
  enable_charset_filter: false
  enable_completion: true
  enable_encoder: true
  enable_sentence: true
  enable_user_dict: true
  encode_commit_history: false
  initial_quality: "-1"
  prefix: ac
  tag: add_user_dict
  tips: "〔自造词〕"
  user_dict: zc
calculator:
  trigger: V
chengyu:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 1.2
  user_dict: "jm_dicts/chengyu"
chinese_english:
  comment_format:
    - "xform/-/ /"
  opencc_config: chinese_english.json
  option_name: chinese_english
  tips: char
cn_en:
  comment_format:
    - "xform/^.+$//"
  db_class: stabledb
  dictionary: ""
  enable_completion: true
  enable_sentence: false
  initial_quality: 0.5
  user_dict: "en_dicts/flypy"
custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 99
  user_dict: custom_phrase
```

```yaml
translator:
  always_show_comments: true
  comment_format:
    {}
  contextual_suggestions: false
  dictionary: custom_self
  disable_user_dict_for_patterns: "^[a-z]{1,6}"
  enable_completion: true
  enable_correction: false
  enable_user_dict: false
  initial_quality: 3
  max_homographs: 5
  max_homophones: 5
  spelling_hints: 50
user_dict_set:
  dictionary: wanxiang
  enable_completion: false
  enable_sentence: false
  enable_user_dict: true
  initial_quality: 1
  spelling_hints: 100
  user_dict: zc
wanxiang_en:
  comment_format:
    - "xform/.*//"
  dictionary: wanxiang_en
  enable_sentence: false
  enable_user_dict: false
  initial_quality: 1.1
```

**Comment by Mikachu2333** [comment]
整明白了，这一大堆全都要patch掉……就是自己的词典里面没有拼音，不知道有没有影响，目前来看没error

```yaml
patch:
  translator/dictionary: custom_self
  radical_reverse_lookup/dictionary: custom_self
  user_dict_set/dictionary: custom_self
  add_user_dict/dictionary: custom_self
```
