### ISSUE TITLE
请问针对 *.schema.yaml 的那些方案选择配置，可以放到 *.custom.yaml 中吗？

### ISSUE THREAD

**Issue by OOKAMISAMA** [amzxyz/rime_wanxiang_pro#9]
一开始用的时候有尝试过，但是好像不生效，不知道是不是我写得不对。
今天 git pull 更新了一下，原先选择的方案又被覆盖了，变回了默认的自然码。
主要痛点是这段，虽然可以用 .gitignore 是屏蔽掉，但是方案有更新的时候，就只能手工去 merge 了，还是不太方便。

![image](https://github.com/user-attachments/assets/d7edab74-c327-4338-a132-905b44cb472c)

**Comment by amzxyz** [comment]
*.custom.yaml 当然可以写，是你自己的事情，项目里面不可以包含custom不然会导致自定义失效

**Comment by OOKAMISAMA** [comment]
请问文件名是使用 wanxiang.custom.yaml 吗?
我这样写 patch 是否正确，我当前写的其他配置是生效的，就是方案选择这块不生效。

```
patch:
  set_shuru_schema:
    __include: algebra_flypy
  set_algebra_fuzhu: 
    __include: fuzhu_zrm
  pro_comment_format:
    fuzhu_code: true
    candidate_length: 1
    fuzhu_type: zrm 
    corrector: true
    corrector_type: "{comment}"
```

**Comment by amzxyz** [comment]
这个还是需要调整一下的，不能二次递归__include，我建议你这块手动修改，其他功能进行patch不然要大改动

**Comment by OOKAMISAMA** [comment]
好的，感谢答疑。

**Comment by amzxyz** [comment]
custom是对整体的patch，所以你应该对algebra进行整个段落的patch而不是对表头操作

**Comment by OOKAMISAMA** [comment]
嗯，我去试试。

**Comment by OOKAMISAMA** [comment]
patch 改成 speller/algebra 整个段落后解决问题啦。

**Comment by amzxyz** [comment]
麻烦贴一下，我相信能对其他人有一定意义

**Comment by OOKAMISAMA** [comment]
wanxiang.custom.yaml 配置自定义输入法方案 patch 内容如下，以小鹤双拼为例
```
patch:
  speller:
    algebra:
      # set_shuru_schema: algebra_flypy，对应 wanxiang.schema.yaml 中的 algebra_flypy 段内容
      - xlit/āáǎàōóǒòēéěèīíǐìūúǔùǖǘǚǜü/aaaaooooeeeeiiiiuuuuvvvvv/
      - xform/ń|ň|ǹ/en/
      - xform/\bn\b/en/   #解决𧗈字拼音n通过双拼en打出来
      - xform/\bng\b/eng/
      - xform/ńg|ňg|ǹg/eng/
      - derive/^([jqxy])u(;.*)$/$1v$2/
      - derive/^([aoe])([ioun])(;.*)$/$1$1$2$3/
      - xform/^([aoe])(ng)?(;.*)$/$1$1$2$3/
      - xform/^(\w+?)iu(;.*)/$1Ⓠ$2/
      - xform/^(\w+?)ei(;.*)/$1Ⓦ$2/
      - xform/^(\w+?)uan(;.*)/$1Ⓡ$2/
      - xform/^(\w+?)[uv]e(;.*)/$1Ⓣ$2/
      - xform/^(\w+?)un(;.*)/$1Ⓨ$2/
      - xform/^(\w+?)uo(;.*)/$1Ⓞ$2/
      - xform/^(\w+?)ie(;.*)/$1Ⓟ$2/
      - xform/^(\w+?)i?ong(;.*)/$1Ⓢ$2/
      - xform/^(\w+?)ing(;.*)/$1Ⓚ$2/
      - xform/^(\w+?)uai(;.*)/$1Ⓚ$2/
      - xform/^(\w+?)ai(;.*)/$1Ⓓ$2/
      - xform/^(\w+?)eng(;.*)/$1Ⓖ$2/
      - xform/^(\w+?)en(;.*)/$1Ⓕ$2/
      - xform/^(\w+?)[iu]ang(;.*)/$1Ⓛ$2/
      - xform/^(\w+?)ang(;.*)/$1Ⓗ$2/
      - xform/^(\w+?)ian(;.*)/$1Ⓜ$2/
      - xform/^(\w+?)an(;.*)/$1Ⓙ$2/
      - xform/^(\w+?)ou(;.*)/$1Ⓩ$2/
      - xform/^(\w+?)iao(;.*)/$1Ⓝ$2/
      - xform/^(\w+?)[iu]a(;.*)/$1Ⓧ$2/
      - xform/^(\w+?)ao(;.*)/$1Ⓒ$2/
      - xform/^(\w+?)ui(;.*)/$1Ⓥ$2/
      - xform/^(\w+?)in(;.*)/$1Ⓑ$2/
      - xform/^sh/Ⓤ/
      - xform/^ch/Ⓘ/
      - xform/^zh/Ⓥ/
      - xlit/ⓆⓌⓇⓉⓎⓊⒾⓄⓅⓈⒹⒻⒼⒽⒿⓀⓁⓏⓍⒸⓋⒷⓃⓂ/qwrtyuiopsdfghjklzxcvbnm/

      # set_algebra_fuzhu: fuzhu_flypy，对应 wanxiang.schema.yaml 中的 fuzhu_flypy 段内容
      - xform/^(.{2}|\w+?);.*?;(.*?);.*$/$1;$2/
      - derive|^(.{2});.*$|$1| # 纯双拼的情况
      - derive|^(.{2});(\w)(\w).*$|$1$2| # 双拼+一位辅助码的情况
      - derive|^(.{2});(\w)(\w).*$|$1[$2| # 双拼+[一位辅助码的情况
      - derive|^(.{2});.*?,(\w)(\w).*$|$1$2| # 双拼+一位辅助码的情况
      - derive|^(.{2});.*?,(\w)(\w).*$|$1[$2| # 双拼+[一位辅助码的情况

      - abbrev|^(.{2});(\w)(\w).*$|$1$2$3| # 双拼+2位辅助码的情况，abbrev类型不可以整句内输入2位辅助码，必须加o或/
      - abbrev|^(.{2});.*?,(\w)(\w).*$|$1$2$3| # 双拼+2位辅助码的情况，abbrev类型不可以整句内输入2位辅助码，必须加o或/

      - derive|^(.{2});(\w)(\w).*$|$1$2$3o| # 整句模式下，输入syffo 出单字 增强单字性能
      - derive|^(.{2});(\w)(\w).*$|$1$2$3/| # 整句模式下，输入syff/ 出单字 增强单字性能
      - derive|^(.{2});.*,(\w)(\w).*$|$1$2$3o| # 整句模式下，输入syffo 出单字 增强单字性能
      - derive|^(.{2});.*,(\w)(\w).*$|$1$2$3/| # 整句模式下，输入syff/ 出单字 增强单字性能
```
